workspace:
  path: /go/src/github.com/appleboy/gorush

pipeline:
  # restore the cache from an sftp server
  restore_cache:
    image: appleboy/drone-sftp-cache
    restore: true
    mount: [ .glide, vendor ]
    ignore_branch: true

  build:
    image: appleboy/golang-testing:${GO_VERSION}
    environment:
      - GOPATH=/go
    commands:
      - make dep_install
      - make vet
      - make lint
      - make build
      - coverage all
      # build binary for docker image
      - make docker_binary_build

  docker:
    image: plugins/docker
    repo: appleboy/gorush
    tags: [ '${DRONE_TAG}' ]
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]

  docker:
    image: plugins/docker
    repo: appleboy/gorush
    tags: [ 'latest' ]
    when:
      event: [ push ]
      branch: [ master ]

  facebook:
    image: appleboy/drone-facebook
    pull: true
    to: 1234973386524610
    when:
      status: [ success, failure ]
      matrix:
        GO_VERSION: 1.7.4

  # rebuild the cache on the sftp server
  rebuild_cache:
    image: appleboy/drone-sftp-cache
    rebuild: true
    mount: [ .glide, vendor ]
    ignore_branch: true
    when:
      branch: master
      matrix:
        GO_VERSION: 1.7.4

services:
  redis:
    image: redis:alpine

matrix:
  GO_VERSION:
    - 1.7.4
    - 1.6.4
