version: "3"


# TODO
# Download and add gorush for your machine at https://github.com/appleboy/gorush/releases
#
# Download the binary to release/linux/amd64/gorush or equivalent


services:
  gorush:
    build:
      context: .
      dockerfile: ./Dockerfile.alpine
    ports:
      - "8088:8088"
    links:
      - redis
    depends_on:
      - redis
    environment:
      # - CORE__CERT_PATHFILE=
      # - CORE__KEY_PATHFILE=
      # - IOS__KEY_FILE=
      - CONFIG_YML=Y29yZToKICBlbmFibGVkOiB0cnVlICMgZW5hYmFsZSBodHRwZCBzZXJ2ZXIKICBhZGRyZXNzOiAiIiAjIGlwIGFkZHJlc3MgdG8gYmluZCAoZGVmYXVsdDogYW55KQogIHBvcnQ6ICI4MDg4IiAjIGlnbm9yZSB0aGlzIHBvcnQgbnVtYmVyIGlmIGF1dG9fdGxzIGlzIGVuYWJsZWQgKGxpc3RlbiA0NDMpLgogIHdvcmtlcl9udW06IDAgIyBkZWZhdWx0IHdvcmtlciBudW1iZXIgaXMgcnVudGltZS5OdW1DUFUoKQogIHF1ZXVlX251bTogMCAjIGRlZmF1bHQgcXVldWUgbnVtYmVyIGlzIDgxOTIKICBtYXhfbm90aWZpY2F0aW9uOiAxMDAKICBzeW5jOiB0cnVlICMgc2V0IHRydWUgaWYgeW91IG5lZWQgZ2V0IGVycm9yIG1lc3NhZ2UgZnJvbSBmYWlsIHB1c2ggbm90aWZpY2F0aW9uIGluIEFQSSByZXNwb25zZS4KICBtb2RlOiAicmVsZWFzZSIKICBzc2w6IGZhbHNlCiAgY2VydF9wYXRoOiAiY2VydC5wZW0iCiAga2V5X3BhdGg6ICJrZXkucGVtIgogIGh0dHBfcHJveHk6ICIiICMgb25seSB3b3JraW5nIGZvciBGQ00gc2VydmVyCiAgcGlkOgogICAgZW5hYmxlZDogZmFsc2UKICAgIHBhdGg6ICJnb3J1c2gucGlkIgogICAgb3ZlcnJpZGU6IHRydWUKICBhdXRvX3RsczoKICAgIGVuYWJsZWQ6IGZhbHNlICMgQXV0b21hdGljYWxseSBpbnN0YWxsIFRMUyBjZXJ0aWZpY2F0ZXMgZnJvbSBMZXQncyBFbmNyeXB0LgogICAgZm9sZGVyOiAiLmNhY2hlIiAjIGZvbGRlciBmb3Igc3RvcmluZyBUTFMgY2VydGlmaWNhdGVzCiAgICBob3N0OiAiIiAjIHdoaWNoIGRvbWFpbnMgdGhlIExldCdzIEVuY3J5cHQgd2lsbCBhdHRlbXB0CgpncnBjOgogIGVuYWJsZWQ6IGZhbHNlICMgZW5hYmFsZSBnUlBDIHNlcnZlcgogIHBvcnQ6IDkwMDAKCmFwaToKICBwdXNoX3VyaTogIi9hcGkvcHVzaCIKICBzdGF0X2dvX3VyaTogIi9hcGkvc3RhdC9nbyIKICBzdGF0X2FwcF91cmk6ICIvYXBpL3N0YXQvYXBwIgogIGNvbmZpZ191cmk6ICIvYXBpL2NvbmZpZyIKICBzeXNfc3RhdF91cmk6ICIvc3lzL3N0YXRzIgogIG1ldHJpY191cmk6ICIvbWV0cmljcyIKICBoZWFsdGhfdXJpOiAiL2hlYWx0aHoiCgphbmRyb2lkOgogIGVuYWJsZWQ6IGZhbHNlCiAgYXBpa2V5OiAiWU9VUl9BUElfS0VZIgogIG1heF9yZXRyeTogMCAjIHJlc2VuZCBmYWlsIG5vdGlmaWNhdGlvbiwgZGVmYXVsdCB2YWx1ZSB6ZXJvIGlzIGRpc2FibGVkCgppb3M6CiAgZW5hYmxlZDogdHJ1ZQogIGtleV9wYXRoOiAiaW9zX2tleS5wZW0iCiAgcGFzc3dvcmQ6ICIiICMgY2VydGlmaWNhdGUgcGFzc3dvcmQsIGRlZmF1bHQgYXMgZW1wdHkgc3RyaW5nLgogIHByb2R1Y3Rpb246IGZhbHNlCiAgbWF4X3JldHJ5OiAwICMgcmVzZW5kIGZhaWwgbm90aWZpY2F0aW9uLCBkZWZhdWx0IHZhbHVlIHplcm8gaXMgZGlzYWJsZWQKICBrZXlfaWQ6ICIiICMgS2V5SUQgZnJvbSBkZXZlbG9wZXIgYWNjb3VudCAoQ2VydGlmaWNhdGVzLCBJZGVudGlmaWVycyAmIFByb2ZpbGVzIC0+IEtleXMpCiAgdGVhbV9pZDogIkcyNU41SktUMzYiICMgVGVhbUlEIGZyb20gZGV2ZWxvcGVyIGFjY291bnQgKFZpZXcgQWNjb3VudCAtPiBNZW1iZXJzaGlwKQoKbG9nOgogIGZvcm1hdDogInN0cmluZyIgIyBzdHJpbmcgb3IganNvbgogIGFjY2Vzc19sb2c6ICJzdGRvdXQiICMgc3Rkb3V0OiBvdXRwdXQgdG8gY29uc29sZSwgb3IgZGVmaW5lIGxvZyBwYXRoIGxpa2UgImxvZy9hY2Nlc3NfbG9nIgogIGFjY2Vzc19sZXZlbDogImRlYnVnIgogIGVycm9yX2xvZzogInN0ZGVyciIgIyBzdGRlcnI6IG91dHB1dCB0byBjb25zb2xlLCBvciBkZWZpbmUgbG9nIHBhdGggbGlrZSAibG9nL2Vycm9yX2xvZyIKICBlcnJvcl9sZXZlbDogImVycm9yIgogIGhpZGVfdG9rZW46IHRydWUKCnN0YXQ6CiAgZW5naW5lOiAicmVkaXMiICMgc3VwcG9ydCBtZW1vcnksIHJlZGlzLCBib2x0ZGIsIGJ1bnRkYiBvciBsZXZlbGRiCiAgcmVkaXM6CiAgICBhZGRyOiAicmVkaXM6NjM3OSIKICAgIHBhc3N3b3JkOiAiIgogICAgZGI6IDAKICBib2x0ZGI6CiAgICBwYXRoOiAiYm9sdC5kYiIKICAgIGJ1Y2tldDogImdvcnVzaCIKICBidW50ZGI6CiAgICBwYXRoOiAiYnVudC5kYiIKICBsZXZlbGRiOgogICAgcGF0aDogImxldmVsLmRiIg==
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
