apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gorush
  namespace: gorush
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: gorush
        tier: frontend
    spec:
      containers:
      - image: appleboy/gorush
        name: gorush
        imagePullPolicy: Always
        ports:
        - containerPort: 8088
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8088
          initialDelaySeconds: 3
          periodSeconds: 3
        env:
        - name: GORUSH_STAT_ENGINE
          valueFrom:
            configMapKeyRef:
              name: gorush-config
              key: stat.engine
        - name: GORUSH_STAT_REDIS_ADDR
          valueFrom:
            configMapKeyRef:
              name: gorush-config
              key: stat.redis.host
        - name: CORE__CERT_PATHFILE
          valueFrom:
            secretKeyRef:
              name: gorush-secret
              key: CORE__CERT_PATHFILE
              optional: true
        - name: CORE__KEY_PATHFILE
          valueFrom:
            secretKeyRef:
              name: gorush-secret
              key: CORE__KEY_PATHFILE
              optional: true
        - name: IOS__KEY_FILE
          valueFrom:
            secretKeyRef:
              name: gorush-secret
              key: IOS__KEY_FILE
              optional: true
        - name: CONFIG_YML
          valueFrom:
            secretKeyRef:
              name: gorush-secret
              key: CONFIG_YML
              optional: true
