core:
  port: "8088"
  notification_max: 100
  production: true

api:
  push_uri: "/api/push"
  stat_go_uri: "/api/status"

android:
  enabled: false
  apikey: ""

ios:
  enabled: false
  pem_cert_path: "cert.pem"
  pem_key_path: "key.pem"
  production: false
