core:
  port: "8088"
  worker_num: 0 # default worker number is runtime.NumCPU()
  queue_num: 0 # default queue number is 8192
  max_notification: 100
  mode: "release"
  ssl: false
  cert_path: "cert.pem"
  key_path: "key.pem"
  http_proxy: "" # only working for GCM server
  pid:
    enabled: false
    path: "gorush.pid"
    override: true

api:
  push_uri: "/send"
  stat_go_uri: "/stat/go"
  stat_app_uri: "/stat/app"
  config_uri: "/config"
  sys_stat_uri: "/sys/stats"
  metric_uri: "/metrics"
  ping_uri: "/stats/ping"
  test_uri: "/stats/test"

android:
  enabled: true
  apikey: "YOUR_API_KEY"
  max_retry: 0 # resend fail notification, default value zero is disabled

ios:
  enabled: false
  key_path: "key.pem"
  password: "" # certificate password, default as empty string.
  production: false
  voip_enabled: false
  voip_key_path: "voipkey.pem"
  voip_password: ""
  voip_production: false
  max_retry: 0 # resend fail notification, default value zero is disabled

web:
  enabled: false
  apikey: "YOUR_GCM_API_KEY"
  max_retry: 0 # resend fail notification, default value zero is disabled

log:
  format: "string" # string or json
  access_log: "stdout" # stdout: output to console, or define log path like "log/access_log"
  access_level: "debug"
  error_log: "stderr" # stderr: output to console, or define log path like "log/error_log"
  error_level: "error"
  hide_token: true

stat:
  engine: "memory" # support memory, redis, boltdb, buntdb or leveldb
  redis:
    addr: "localhost:6379"
    password: ""
    db: 0
  boltdb:
    path: "bolt.db"
    bucket: "gorush"
  buntdb:
    path: "bunt.db"
  leveldb:
    path: "level.db"
